name: Publish to GitHub Packages

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '9' # Matches the Gradle config
          cache: 'gradle'

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and publish package
        env:
          BASED_ANDROID_USERNAME: ${{ secrets.GITHUB_ACTOR }}
          BASED_ANDROID_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
